### PR TITLE
Don't spam our IRC channel with your fork's CI messages

### PR DESCRIPTION
**Pull request by CounterPillow**

### CODE REVIEW

**Comment by agrif** [comment]
Admittedly, this is a pretty silly thing for travis to do by default...

**Comment by RedSparr0w** [comment]
how do i disable it? i never set it up to use travis.

**Comment by RedSparr0w** [comment]
Seems to already be disabled..
image
image

**Comment by RedSparr0w** [comment]
Sorted, for some reason builds were enabled on travis-ci.com, but not travis-ci.org.
🤦‍♂️

**Pull request closed without merging**
